language: java

env:
  global:
    - TERM=dumb
    - secure: "PKPbmZBUf44wyGaSrEU/Qrd4JiBonfxIOLvx9uqLcWX/rZtkr1UtA2glWOQldu8lSvnAUIRGuPQzRXIG8cSgnayWHrnJMW5o139sEW4mnGDciU/YORZSOHCmzQiqy35qPGjFk15qyjnyRgFs7KGlJ1PF0EqmHyFyFcsg/SxoACm1gJbbGMzmE9+mUkb/WMCYHhbwUabvxaoMm5bjuWtnp5dfQfmwdXIyuBw0bNxAzFDEYq/vKyyDPdCuB/1bRfMKYn1h6/Ge1gzwLIQtxOUNG280ZbFbN13HS50ya43d+YJ0Ihs+fx6vdRZofY09IcL0DEuQh01OALnJFGNAZw7o0qTJSstl836Wxt+R8wwmPq2X0DYnpCoZlXpwJq/CnpwcCuRvQprBum5Uq+IRy1FXsjeoGvCHmqHqzJxpr2QI4YU6xLj4ChqdzioOnUQZXTzddYrLLoTIly51d2fX7mnA5q1Ov0nGFWUh8CfjzoUT5yjOij//yTevn2tTDM2LO4f71xQdJiuWrzZARfHYqJL+v21mAmrYp/2gyC/GK5khCv7LdokF8g5iEX6tqdNHSn9uaudZE4jvoJj68uomNqV5sZZRMoANXx6BUXYe2EJ8OCAudMrxj8KPv2DCmqCCv4n7GJR4tdlZ9wHaxMGqZkxwyS55U0u0fa7UZ33eE3Ui8jo="
    - secure: "l5HUxQ0uWW7UpQ3Dw7MFiRVMx7V8Fwz9rwp9u8nJtlyX0Fid3AtMpE6+y4ozf2Z+iGU9WLLJW7coNl/bOKCkh3qd3KODAlxSqf2GmxTX1M/xiB6EkOsx999aeFIM62LFtfNpSU+uWoQKofcqdDjdF1TntGnYyUaIE2tC88eDpI5iNYa2FsYDCQw6AOS13+0n0b7DP5vse1PbUw57aKcEsyXXMZpExOhkho9CojqIzSluT65fIljgsSCZNRwwnhd7KBRwSJgQTm2skK4IawnweKy+R9tn9vmUyxSb2uwwXffTd+3SNc9pyU0IQ0c7M/qAXl5qC5mO3CGtvr40UHTufYw+93Z9oFzZmAlmW5kbGizC1G/AU91Lw8BSRSYEl8sX0Ydj9FkLOzCwTOkZBKw0H38Km5qAsYPd6weruxyTUA4qV+NRyqU/k9hS1/lKnYNsg2FLfydKkQAG6btI2yMG0O6y1WaBBGcI+LCXgJ3UZqIlW+VFA2TzqZ9Jg71vlYho1haT+znaT01VbNtAvMZEIBvd0gDI5cpvU1DeeICA7j7aqFlL37Jo3uuEAMOpVFqwOtlPwkLT8FKcXFQInE9ZnKWHh0vpM56+Yhg88ADuege03XsHC7y6He8xuQQW4RgEBW+M1dfHiig/oCLvdtclH6jFeWEh6rLJtG4zHt/KcZk="

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
      jdk: openjdk11
      env:
        - BOWLER_KINEMATICS_NATIVE_OS_NAME=linux
    - os: osx
      osx_image: xcode10.1
      env:
        - BOWLER_KINEMATICS_NATIVE_OS_NAME=macos

script:
  - ./gradlew check --stacktrace -PlogTests

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - echo $TRAVIS_TAG
  - echo $$TRAVIS_PULL_REQUEST
  - if [ $TRAVIS_TAG && "$TRAVIS_PULL_REQUEST" = "false" ]; then ./gradlew bintrayUpload; fi
