language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
      jdk: openjdk11
    - os: osx
      osx_image: xcode10.1

env:
  - TERM=dumb

before_install:
  - mkdir ~/.gradle
  - touch ~/.gradle/gradle.properties
  - openssl aes-256-cbc -K $encrypted_bb837da2b164_key -iv $encrypted_bb837da2b164_iv -in gradle.properties.enc -out ~\/.gradle/gradle.properties -d

script:
  - ./gradlew check --stacktrace -PlogTests

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew bintrayUpload
