version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --stacktrace

test_script:
  - gradlew.bat check --stacktrace

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: true
